---
version: "3.9"
services:

  book-a-book-eureka:
    image: aleixmt/book-a-book-eureka:latest
    ports:
      - "0.0.0.0:8762:8761"
    restart: unless-stopped
    pull_policy: always
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent localhost:8761/actuator/health | grep -q UP"]
      interval: 15s
      retries: 5
      timeout: 10s
      start_period: 5s

  postgres_operador:
    image: postgres
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
      - POSTGRES_PASSWORD=chemistry
      - POSTGRES_USER=aleixmt
      - POSTGRES_DB=book-a-book-operador
    ports:
      - "0.0.0.0:5434:5432"
    restart: unless-stopped

  postgres_buscador:
    image: postgres
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
      - POSTGRES_PASSWORD=chemistry
      - POSTGRES_USER=aleixmt
      - POSTGRES_DB=book-a-book-buscador
    ports:
      - "0.0.0.0:5433:5432"
    restart: unless-stopped


  book-a-book-buscador:
    image: aleixmt/book-a-book-buscador:latest
    ports:
      - "0.0.0.0:8082:8081"
    depends_on:
      book-a-book-eureka:
        condition: service_healthy
      postgres_buscador:
        condition: service_started
    #restart: unless-stopped
    pull_policy: always

  book-a-book-operador:
    image: aleixmt/book-a-book-operador:latest
    ports:
      - "0.0.0.0:8084:8083"
    depends_on:
      book-a-book-eureka:
        condition: service_healthy
      postgres_operador:
        condition: service_started
    #restart: unless-stopped
    pull_policy: always


